name: first
on:  
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
    ubuntu:
        name: First job
        runs-on: ubuntu-latest
        steps:    
        - name: Print a date on Ubantu
        - run: date  
   