name: first
on:  
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:   
        - name: Print a date on Ubuntu        
          run: date
    windows:
        runs-on: windows-latest
        steps:
        - name: Print a date on Windows
          run: date
    macos:
        name: Print a date on MacOS
        runs-on: macos-latest
        steps:
        - name: Print a date on MacOS
          run: date       
    depends:
        name: Forth job
        needs: [ubuntu, windows, macos]
        runs-on: ubuntu-latest
        steps:
        - name: Print a date on Ubantu
          run: date
   