name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout files
      uses: Bhacaz/checkout-files@v2
      with:
        files: py-app
        
    - name: Install dependencies
      run: pub get
      working-directory: py-app    

    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      working-directory: py-app 
      
      
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
      working-directory: py-app 
      
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
      working-directory: py-app 
        
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
      working-directory: py-app 