name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
        run:
           working-directory: ./py-app
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4.4.0
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
