name: first
on:  
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:    
        - name: Checks-out 
          run: |
            echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
            echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
